#!/bin/python

import os
import sys
from datetime import datetime

import torch

import fileutils
import dataset
from trainer import NeuralNetTrainer

####
# Customizable data maker and data destination
from data_makers.dm_coinbase import make_input
DATA_FILE_PATH = "data/live/coinbase/data.csv"

# from data_makers.dm_cointelegraph import make_data
# DATA_FILE_PATH = "data/live/cointelegraph/amCharts.csv"
####


EXP_ROOT_DIR = "experiments"


if __name__ == "__main__":
    print()
    print("Content-type:text/html\r\n\r\n")
    
    config_file_path = None
    experiment_dir_path = None

    mode = 'p'
    
    experiment_name = '2'
    experiment_dir_path = os.path.join(EXP_ROOT_DIR, experiment_name)

    # Check experiment exists
    if not os.path.exists(experiment_dir_path):
        raise Exception(experiment_dir_path, " doesn't exist:")
    
    # Check config file exists
    config_file_path = os.path.join(experiment_dir_path, "config.json")
    if not os.path.isfile(config_file_path):
        raise Exception("config.json doesn't exist:")

    config = fileutils.get_config_from_file(config_file_path)
    
    
    # Prep data
    X, y, predict_serie, last_timestamp, last_close = make_input(config["data"]["time_interval"], 
                   config["model"]["input_feature_size"], 
                   config["model"]["output_feature_size"], 
                   config["data"]["input_serie_len"], 
                   config["data"]["output_serie_len"])

    # Prep network
    trainer = NeuralNetTrainer(config_file_path, experiment_dir_path, print_info=False)

    if mode == 't':
        dataloader = dataset.get_dataloader_from_tensor(config, X, y)
        trainer.test_dataloader = dataloader
        trainer.test("_test")
    elif mode == 'p':
        prediction = trainer.single_predict(predict_serie)
        print("<br>AI prediction output:", prediction)
        print("<br>Last timestamp:", str(int(last_timestamp)))
        print("<br>\tIn PST:", datetime.utcfromtimestamp(last_timestamp - 25200).strftime('%Y-%m-%d %H:%M:%S'))
        print("<br>Last close @ {:.3f} USD".format( last_close ))
        print("<br>Limit sell @ {:.3f} USD".format( last_close * (prediction[0] / 1000 + 1) ))
        print("<br>Limit buy @ {:.3f} USD".format( last_close * (prediction[1] / 1000 + 1) ))
        